//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Nullable<int> accID { get; set; }
        public int accNum { get; set; }
        public Nullable<int> net { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual User User { get; set; }
    }
}
